---
#################################################
# ConfigMap for index.html for mydata v2
#################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mydata-cm-v2
data:
  index.html: |
    <body bgcolor="blue">
      <center>
        <h1>HashiCorp Squad</h1>
        <h1>Version 2</h1>
      </center>
    </body>
---
#################################################
# Deployment: mydata v2
#################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydata-v2
  labels:
    app: mydata
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydata
      version: v2
  template:
    metadata:
      labels:
        app: mydata
        version: v2
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9102"
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/service-meta-version": "v2"
        "consul.hashicorp.com/connect-service-port": "80"
    spec:
      containers:
      - image: nginx
        name: mydata
        volumeMounts:
        - name: index-html
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: index-html
        configMap:
          name: mydata-cm-v2
